FROM cnstark/pytorch:2.0.1-py3.10.11-cuda11.8.0-ubuntu22.04

WORKDIR /workspace

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY requirements.txt requirements.txt
COPY resources/sources.list /etc/apt/sources.list
COPY resources/checkpoints/ /root/.cache/torch/hub/checkpoints/
COPY resources/pydensecrf /workspace/pydensecrf


RUN apt update && apt install -y libgl1-mesa-glx libglib2.0-dev

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt

WORKDIR /workspace/pydensecrf
RUN python setup.py install

WORKDIR /workspace
