FROM cnstark/pytorch:2.0.1-py3.10.11-cuda11.8.0-ubuntu22.04

WORKDIR /workspace

COPY resources/checkpoints/ /root/.cache/torch/hub/checkpoints/

RUN apt update && apt install -y libgl1-mesa-glx libglib2.0-dev jq

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip install pandas matplotlib seaborn ujson opencv-python albumentations jsonschema ml_collections
RUN pip install torchmetrics torchsummary pytorch-msssim