from ._utils import (
    deeplabv1,
    deeplabv2_mobilenetv2,
    deeplabv2_resnet101,
    deeplabv2_xception,
    deeplabv3_mobilenetv2,
    deeplabv3_mobilenetv3_large,
    deeplabv3_mobilenetv3_small,
    deeplabv3_plus_mobilenetv2,
    deeplabv3_plus_mobilenetv3_large,
    deeplabv3_plus_mobilenetv3_small,
    deeplabv3_plus_resnet50,
    deeplabv3_plus_resnet101,
    deeplabv3_plus_xception,
    deeplabv3_resnet50,
    deeplabv3_resnet101,
    deeplabv3_xception,
)
